### ISSUE TITLE
Proposal for create ShardingSphere ui project

### ISSUE THREAD

**Issue by beckhampu** [sharding-sphere/sharding-ui#3]
Sharding-ui is the management console of ShardingSphere, providing ability of configuration, orchestration, etc.  It will use SFB(Separation of Front and Back ends) framework. The Frontend based on vue and use the UI Toolkit element-ui. And the backend is a standard spring boot project.

Task Here：
- [x] Backend task
     - [x] project init（maven）
     - [x] user management
     - [x] config center management
     - [x] configuration management
         - [x] schema configuration（rule and datasoucre）
         - [x] config map configuration
         - [x] props configuration
         - [x] authentication configuration for Sharding-Proxy
     - [x] orchestration operation
- [x] Frontend task
     - [x] project init（vue-cli）
     - [x] code rule（eslint）
     - [x] vue component
     - [x] Interface layout
     - [x] pages
- [x] Other task
     - [x] project build and packaging
     - [x] project doc
     
 Any comments are welcomed！

**Comment by beckhampu** [comment]
@wqzwh , Let's finish it together!

**Comment by wqzwh** [comment]
@beckhampu 👌
