### ISSUE TITLE
About the front-end development proposal for creating a ShardingSphere ui project

### ISSUE THREAD

**Issue by wqzwh** [sharding-sphere/sharding-ui#4]
Sharding-ui is the management console of ShardingSphere, providing ability of configuration, orchestration, etc. It will use SFB(Separation of Front and Back ends) framework. The Frontend based on vue and use the UI Toolkit element-ui. And the backend is a standard spring boot project.

Frontend task here：

Core technology framework
* vue 2.5.2
* element-ui 2.4.9

- [x] layout structure
- [x] header component
- [x] avator component
- [x] menu component
- [x] registration center configuration layout
    - [x] button component
    - [x] table component
    - [x] modal component
    - [x] mock data logic addition
- [x] configuration management
    - [x] tab component
    - [x] schema module
    - [x] authentication module
    - [x] configmap module
    - [x] props module
- [x] common module
    - [x] axios addition
    - [x] config management
    - [x] constant addition
- [x] multi-language support
- [x] add unit test
- [x] add yaml editor
- [x] add proxy config
- [x] add orchestration

Accept the needs discussion！

**Comment by wqzwh** [comment]
@beckhampu I have completed the following these for the time being.

- [x] layout structure
- [x] header component
- [x] menu component
- [x] button component
- [x] table component

As of this commit c04dd35c86e06f6c8014818ce169ee481b8882b2

**Comment by wqzwh** [comment]
@beckhampu I have completed the following these for the time being.

- [x] modal component

Add Dialog components
Improve table display
Menu connection routing added
  
commit cbe4d5fc2182c9d98ee35e7c84d4d6b44ad645c6
commit 140c088b5539d91ba241e87f5501d511c1a9ed3f

**Comment by wqzwh** [comment]
@beckhampu I have completed the following these for the time being.

- [x] tab component
 - [x] tree component

Add operational feedback tips 78ee01af3577b49a423dc309ec30e4db008f0553
Button add hint feedback b245d2ac44658160adc4da04a60e1e28e62dad2e
Add configuration management page, routing settings,
navigation highlighting e561ac3d70e4eea2dba1b7d5784150892dad56f7

**Comment by wqzwh** [comment]
@beckhampu I have completed the following these for the time being.

- [x] axios addition

Add axios custom package 35861226bb354559f9c10f6ead57e8916484ef0a

**Comment by wqzwh** [comment]
@beckhampu I have completed the following these for the time being.

 - [x] mock data logic addition

Add registry page real interface logic 960303192d10a0b005a676104c217d80dd88e4f2

**Comment by wqzwh** [comment]
@beckhampu Completed the following

-[x] add unit test
-[x] add yaml editor

**Comment by wqzwh** [comment]
@beckhampu Completed the following
- [x] add schema module

**Comment by wqzwh** [comment]
- [x] add orchestration

**Comment by beckhampu** [comment]
@wqzwh ，I have completed the user authentication function，you can try it！

**Comment by wqzwh** [comment]
> @wqzwh ，I have completed the user authentication function，you can try it！

ok

**Comment by wqzwh** [comment]
@beckhampu  completed this following

1. Loss of footer on login page
2. Add a login function, which is to clear the access-token in the front-end local storage and log in again.
3. The home page top shows the correct username
4. Top on the main page plus the name of registry-center that shows the current connection
5. The proxy of dev can also be deleted. The host of Dev and prod is defined as localhost:8088

**Comment by wqzwh** [comment]
complete this following

1. Logout is displayed in Chinese.
2, the head does not display the name of the currently connected registry
3. Digest is changed to non-required when adding a new registration center
4, the enable operation in orchestration is passed true
5, BASE_API defined in dev.env.js can be removed
6, the previous communication is a bit different, the front-end startup is still 8080, is to access the back-end api changed to localhost: 8088
7, utils.js JSONP_HOST delete
